# Generated by Django 2.0.13 on 2019-09-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_subcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubCourse')),
            ],
        ),
    ]
