# Generated by Django 2.0.13 on 2019-09-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190929_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='ClassAvailability',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='CourseDuration',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='DemoClass',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='Overview',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='TrainingMethodology',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='coursename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
    ]
