# Generated by Django 2.0.13 on 2019-09-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190929_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='name',
        ),
    ]
