# Generated by Django 2.0.13 on 2019-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_coursecontent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
